---
- hosts: all
  become: yes
  tasks:
    # Task 1: Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Task 2: Install Kube tools
    - name: Install kubeadm, kubelet, kubectl
      apt:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present
        update_cache: yes
        # This assumes you have already configured the Kubernetes APT repository.
        # If not, you must add a previous task to configure the repository first.
