apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
  namespace: microservices
  labels:
    app: web-app
    version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  
  minReplicas: 1
  maxReplicas: 5
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 1
        periodSeconds: 30
    
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-hpa-info
  namespace: microservices
data:
  target-deployment: "web-app"
  min-replicas: "1"
  max-replicas: "5"
  cpu-threshold: "75%"
  memory-threshold: "85%"
