apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-job-hpa
  namespace: microservices
  labels:
    app: worker-job
    version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-job
  
  minReplicas: 1
  maxReplicas: 3
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-job-hpa-info
  namespace: microservices
data:
  target-deployment: "worker-job"
  min-replicas: "1"
  max-replicas: "3"
  cpu-threshold: "80%"
  memory-threshold: "90%"
