apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: microservices

# Resources to include
resources:
- 01-namespace.yaml
- 02-mysql.yaml
- 03-redis.yaml
- 04-api-server.yaml
- 05-web-app.yaml
- 06-worker-job.yaml

# Common labels applied to all resources
commonLabels:
  app: microservices-platform
  version: v1.0
  managed-by: kustomize

# Common annotations
commonAnnotations:
  documentation: "Microservices Layer - Production Kubernetes Platform"
